h_header = '''
/* ************************************************************************** */
/*                                                                            */
/*                    Mentor Graphics Corporation                             */
/*                        All rights reserved                                 */
/*                           NBYX Created                                     */
/* ************************************************************************** */
/*                                                                            */
/*  Description:   header file for  signals and frames                        */
/*                                                                            */
/* ************************************************************************** */
/*                                                                            */
/*                                                                            */
/* ************************************************************************** */
/* Auto generated by dbcConvertTool.py                                        */
/*                                                                            */
/* ************************************************************************** */


'''

def CreateH(dbclist,node):
    hfile = open("target.h","w+")
    hfile.writelines(h_header)

    print("h file is going")

    hfile.flush()
    hfile.close()

    return
    