globalstring = ''

net_header = '''
/* ************************************************************************** */
/*                                                                            */
/*                    Mentor Graphics Corporation                             */
/*                        All rights reserved                                 */
/*                           NBYX Created                                     */
/* ************************************************************************** */
/*                                                                            */
/*  Description:   Network file for Volcano 7.2                               */
/*  ECU:           SCU                                                        */
/*                                                                            */
/* ************************************************************************** */
/*                                                                            */
/*                                                                            */
/* ************************************************************************** */
/*                                                                            */
/* Auto generated by dbc2vtp tool                                             */
/* ************************************************************************** */

network_file;
volcano version "7.2"; 

'''

def Frame_Process(fra,dir):
    global globalstring
    globalstring = ''

    globalstring = "\r\nsignal frame " + fra[1] + "{\r\n"
    if dir == 1:
        globalstring += "       received;\r\n"
    else:
        globalstring += "       todo;\r\n" 
    globalstring += "       frame size " + fra[3] +" bytes;\r\n"
       
    #for i in range(len(fra) - 4):
        #print(i)
        


    return




def Net_Generate(dbc,masternode,filename):
    outfile = open(filename+".net", "w+")
    outfile.writelines(net_header)

    for i in range(len(dbc)):
        if dbc[i][0] == masternode:
            Frame_Process(dbc[i], 0)
        else:
            Frame_Process(dbc[i], 1)
        outfile.writelines(globalstring)

    outfile.flush()
    outfile.close()

    return