pri_header = '''
/* ************************************************************************** */
/*                                                                            */
/*                    Mentor Graphics Corporation                             */
/*                        All rights reserved                                 */
/*                           NBYX Created                                     */
/* ************************************************************************** */
/*                                                                            */
/*  Description:   pri file for Volcano 7.2                                  */
/*                                                                            */
/* ************************************************************************** */
/*                                                                            */
/*                                                                            */
/* ************************************************************************** */
/* Auto generated by dbcConvertTool.py                                        */
/*                                                                            */
/* ************************************************************************** */


'''

def CreatePri(dbclist,node):
    prifile = open("target.pri","w+")
    prifile.writelines(pri_header)

    print("pri file is going")

    prifile.flush()
    prifile.close()

    return